path = "app/layout.tsx"
with open(path, "r", encoding="utf-8") as f:
    c = f.read()
old = '''export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};'''
new = '''export const metadata: Metadata = {
  title: "Property India Hub - Real Estate Projects in NCR, UP, Rajasthan & Uttarakhand",
  description: "Property India Hub offers verified residential and commercial property listings across Noida, Greater Noida, Ghaziabad, Mathura, Vrindavan, Ayodhya, Jageshwar Dham, Behror, and more. Book a free site visit today.",
};'''
if old not in c:
    print("MISMATCH - manual check needed")
else:
    c = c.replace(old, new)
    with open(path, "w", encoding="utf-8") as f:
        f.write(c)
    print("DONE_META")
